function Export-DecomRemediationPlan {
    param([object[]]$Findings, [string]$Path, [pscustomobject]$Context)

    $clientName  = if ($Context.ClientName)   { $Context.ClientName }   else { 'Not specified' }
    $engId       = if ($Context.EngagementId) { $Context.EngagementId } else { 'Not specified' }
    $assessor    = if ($Context.Assessor)     { $Context.Assessor }     else { 'Not specified' }
    $runDate     = Get-Date -Format 'yyyy-MM-dd HH:mm:ss UTC'
    $modeDisplay = $Context.Mode

    $header = @"
# Entra Identity Decommissioning — Remediation Plan
## Rev1.1 Consultant Readiness

| Field          | Value                  |
|----------------|------------------------|
| Client         | $clientName            |
| Engagement ID  | $engId                 |
| Assessor       | $assessor              |
| Assessment Date| $runDate               |
| Mode           | $modeDisplay           |

> **Safety Note:** This plan documents recommended remediation actions identified during an Assessment-mode run.
> This plan does not execute any actions. All remediation requires manual review and explicit approval before execution.

---

## Remediation Actions

"@

    $actionItems = $Findings |
        Where-Object { $_.Severity -in 'Critical','High' } |
        Sort-Object { -$_.RiskScore }

    $actionBlocks = [System.Text.StringBuilder]::new()
    $n = 1
    foreach ($finding in $actionItems) {
        $actionId = "ACT-{0:D3}" -f $n
        $null = $actionBlocks.Append(@"
### $actionId — $($finding.FindingId): $($finding.DisplayName)

| Field                | Value                                                                 |
|----------------------|-----------------------------------------------------------------------|
| Action ID            | $actionId                                                             |
| Finding ID           | $($finding.FindingId)                                                 |
| Severity             | $($finding.Severity) (Risk Score: $($finding.RiskScore))              |
| Object Type          | $($finding.ObjectType)                                                |
| Object ID            | $($finding.ObjectId)                                                  |
| Display Name         | $($finding.DisplayName)                                               |
| Evidence             | $($finding.Evidence)                                                  |
| Recommended Action   | $($finding.RecommendedAction)                                         |
| Business Owner       | [To be confirmed]                                                     |
| Approval Required    | Yes                                                                   |
| Approval Status      | PendingReview                                                         |
| Execution Command    | [Requires ExecuteRemediation mode — not generated in Assessment]      |
| Rollback Note        | [Document current state before execution]                             |
| Evidence Reference   | $($finding.FindingId)                                                 |

---

"@)
        $n++
    }

    $footer = @"
## Notes

- All actions in this plan require explicit client approval before execution.
- This plan was generated by Entra Identity Decommissioning Control Plane Rev1.1.
- For questions about this plan, contact the assessor listed above.
- To execute approved remediation actions, re-run the tool with ``-Mode ExecuteRemediation`` after obtaining approvals.

*Entra Identity Decommissioning Control Plane Rev1.1 — Consultant Advisory Tool*
"@

    $content = $header + $actionBlocks.ToString() + $footer
    Set-Content -Path $Path -Value $content -Encoding UTF8
}
